# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 18:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Compiler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='submission_time',
            field=models.TimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 2, 18, 6, 58, 21000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
