# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compiler', '0002_solution_submission_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='output',
        ),
    ]
