# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-02 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compiler', '0005_timerproblem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerproblem',
            name='time_init',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
