# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-02 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compiler', '0006_auto_20161002_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='submission_name',
        ),
    ]
