# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-02 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compiler', '0007_remove_solution_submission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
